### PR TITLE
Create links from Grafana to RHVM

### PR DESCRIPTION
**Pull request by avlitman**
We want to create links FROM Grafana to RHVM,
So that the user can easily see information about entities on both portals.

Bug-Url: https://bugzilla.redhat.com/1925878
Signed-off-by: Aviv Litman <alitman@redhat.com>

### CODE REVIEW

**Comment by avlitman** [comment]
rpm's are verified.

Hi @sradco, I would appreciate your review.

**Comment by avlitman** [comment]
Verified.

**Comment by michalskrivanek** [comment]
shirly approved c0c7c3556722417dd99872f7dae7c905a0bddba2 but then you pushed an update so it doesn't consider it approved. maybe need/want to set an option in projectg setting to invalidate approvals?
OST cares about running the exact commit that was approved

**Comment by avlitman** [comment]
> shirly approved [c0c7c35](https://github.com/oVirt/ovirt-dwh/commit/c0c7c3556722417dd99872f7dae7c905a0bddba2) but then you pushed an update so it doesn't consider it approved. maybe need/want to set an option in projectg setting to invalidate approvals? OST cares about running the exact commit that was approved

Thanks @michalskrivanek, I rebased the pr on top of master after Shirly's review.
Since I'm the only developer on the team, I will not always need reviews. Martin recently added the option to merge without approval (the merge button is red in this case).

Maybe there is a way to set ost to run when called?
Or you think it's better to set the option in the project setting to invalidate approvals?

**Review by mwperina — APPROVED** [review]

**Pull request merged**
