### PR TITLE
WIP:Upgrade the Talend to latest version

### PR DESCRIPTION
**Pull request by avlitman**
Upgrade the Talend to latest version
that supports OpenJDK 11 (8.0.1).

Bug-Url: https://bugzilla.redhat.com/1774013

### CODE REVIEW

**Comment by sradco** [comment]
@avlitman please add a description to the first comment and describe what this PR is about.

**Comment by sradco** [comment]
@avlitman It seems this is a duplicate PR. https://github.com/oVirt/ovirt-dwh/pull/7.

**Comment by avlitman** [comment]
> @avlitman It seems this is a duplicate PR. #7.

This is a test pr. I'm testing 2 different ways to upgrade, since it's a lot of files and hard to commit amend each time.

**Pull request closed without merging**
