### PR TITLE
packaging: setup: Filter from logs secrets from otopi answer files

### PR DESCRIPTION
**Pull request by didib**
For details, see https://github.com/oVirt/ovirt-engine/pull/585 .

Change-Id: Ided28013bc854474dc18ec4dfd4e20884945f86c
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

### CODE REVIEW

**Comment by avlitman** [comment]
LGTM.
Note that I did not verify this PR only review.

**Review by avlitman — APPROVED** [review]

**Review by mwperina — APPROVED** [review]
+1

**Comment by avlitman** [comment]
@didib Should we wait for the engine patch to be merged first?

**Comment by didib** [comment]
> @didib Should we wait for the engine patch to be merged first?

Yes. I talked with @mwperina today and agreed to postpone merging of all of the patches till next week.

**Pull request merged**
